### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Kridoo** [sylan215/compress-with-tinypng#1]
是否可以将压缩完的图 放回原来的目录并且覆盖原有文件，具体思路是什么

**Comment by sylan215** [comment]
可以的，把代码中的这一句
output_path = os.path.join(get_file_dir(input_file), 'tinypng')
改成
output_path = get_file_dir(input_file)
就行了

Kridoo <notifications@github.com> 于2018年11月27日周二 上午11:55写道：
